# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Compositional Layout and Combine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Compositional Layout and Combine
	pod 'Kingfisher', '~> 7.0'
end
